export class AudioSystem{
 constructor(settings){this.settings=settings;this.ctx=null;this.last=new Map();this.bgmTimer=null;this.bgmGain=null;this.pendingTheme=null;this.duckTimer=null;this.step=0;}
 unlock(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(C){this.ctx=new C();this.bgmGain=this.ctx.createGain();this.bgmGain.gain.value=this.bgmLevel();this.bgmGain.connect(this.ctx.destination);}}this.ctx?.resume();if(this.pendingTheme&&!this.bgmTimer)this.startBgm(this.pendingTheme);}
 bgmLevel(){return Math.max(.0001,this.settings.masterVolume*this.settings.bgmVolume*.08);}
 startBgm(theme='renaissance'){this.pendingTheme=theme;this.stopBgm(false);if(!this.ctx||!this.settings.bgmEnabled)return;const scales={renaissance:[261,329,392,523],baroque:[220,277,330,440],romantic:[196,247,294,392],impressionist:[293,349,440,523],postimpressionist:[246,311,370,493],modern:[220,261,329,415],surreal:[185,233,311,370],boss:[146,220,293,349]}[theme]||[220,277,330,440];this.step=0;const play=()=>{if(!this.ctx||!this.settings.bgmEnabled)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),now=this.ctx.currentTime;o.type=theme==='modern'||theme==='surreal'?'triangle':'sine';o.frequency.value=scales[this.step++%scales.length];g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(.12,now+.04);g.gain.exponentialRampToValueAtTime(.001,now+.55);o.connect(g).connect(this.bgmGain);o.start(now);o.stop(now+.6);};play();this.bgmTimer=setInterval(play,650);}
 stopBgm(clearPending=true){if(this.bgmTimer)clearInterval(this.bgmTimer);this.bgmTimer=null;if(clearPending)this.pendingTheme=null;}
 duck(ms=1800){if(!this.bgmGain)return;clearTimeout(this.duckTimer);const now=this.ctx.currentTime;this.bgmGain.gain.cancelScheduledValues(now);this.bgmGain.gain.setTargetAtTime(this.bgmLevel()*.25,now,.05);this.duckTimer=setTimeout(()=>this.bgmGain?.gain.setTargetAtTime(this.bgmLevel(),this.ctx.currentTime,.12),ms);}
 tone(name='select'){if(!this.ctx||!this.settings.sfxEnabled)return;const now=performance.now();if(now-(this.last.get(name)||0)<90)return;this.last.set(name,now);const spec={select:[520,.06],turn:[660,.12],correct:[780,.16],wrong:[180,.2],hit:[110,.08],ultimate:[880,.42],warning:[240,.18],ko:[90,.5],unlock:[1040,.5]}[name]||[440,.1];const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=name==='hit'?'sawtooth':'sine';o.frequency.setValueAtTime(spec[0],this.ctx.currentTime);g.gain.setValueAtTime(.001,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(Math.max(.001,this.settings.masterVolume*this.settings.sfxVolume*.16),this.ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+spec[1]);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+spec[1]+.02);}
}
