import { ARTIST_MAP } from '../data/artists.js';import { STAGES } from '../data/stages.js';
export class BattleRenderer{
 constructor(canvas,settings){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.settings=settings;this.fighters=[];this.stage='renaissance';this.particles=[];this.running=false;this.hit=null;this.time=0;this.resize=()=>this.fit();addEventListener('resize',this.resize);this.fit();}
 fit(){const d=Math.min(devicePixelRatio||1,2),r=this.canvas.getBoundingClientRect();this.canvas.width=Math.max(1,r.width*d);this.canvas.height=Math.max(1,r.height*d);this.ctx.setTransform(d,0,0,d,0,0);this.w=r.width;this.h=r.height;}
 setBattle(fighters,stage){this.fighters=fighters;this.stage=stage;this.particles=[];if(!this.running){this.running=true;requestAnimationFrame(t=>this.frame(t));}}
 attack(side,move,onImpact){const duration=move.id==='ultimate'?1900:move.id==='heavy'?850:550;this.hit={side,move,start:performance.now(),duration,impacted:false,onImpact};}
 burst(x,y,color,count=24){const scale=this.settings.effectLevel==='full'?1:this.settings.effectLevel==='simple'?.45:0;for(let i=0;i<count*scale;i++)this.particles.push({x,y,vx:(Math.random()-.5)*8,vy:(Math.random()-.7)*7,life:1,color,size:2+Math.random()*5});}
 frame(t){if(!this.running)return;this.time=t;this.draw();requestAnimationFrame(n=>this.frame(n));}
 draw(){const c=this.ctx,w=this.w,h=this.h,s=STAGES[this.stage]||STAGES.renaissance,g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,s.colors[0]);g.addColorStop(.62,s.colors[1]);g.addColorStop(1,s.colors[2]);c.fillStyle=g;c.fillRect(0,0,w,h);c.globalAlpha=.16;c.strokeStyle='#fff';for(let x=0;x<w;x+=w/9){c.beginPath();c.moveTo(w/2,h*.4);c.lineTo(x,h);c.stroke()}c.globalAlpha=1;c.fillStyle='#0007';c.fillRect(0,h*.76,w,h*.24);c.fillStyle='#ffffffaa';c.font='12px Georgia';c.fillText(s.name,16,24);
  const prog=this.hit?Math.min(1,(performance.now()-this.hit.start)/this.hit.duration):0;this.fighters.forEach((f,i)=>this.drawFighter(f,i,prog));
  if(this.hit){const impact=this.hit.move.id==='ultimate'?.72:.55;if(prog>=impact&&!this.hit.impacted){this.hit.impacted=true;const side=this.hit.side,x=side===0?w*.73:w*.27;this.burst(x,h*.6,ARTIST_MAP[this.fighters[side].artistId]?.color||'#fff',this.hit.move.id==='ultimate'?85:35);this.hit.onImpact?.();}if(prog>=1)this.hit=null;}
  this.particles=this.particles.filter(p=>p.life>0);for(const p of this.particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.16;p.life-=.025;c.globalAlpha=p.life;c.fillStyle=p.color;c.fillRect(p.x,p.y,p.size,p.size)}c.globalAlpha=1;
 }
 drawFighter(f,i,prog){const c=this.ctx,a=ARTIST_MAP[f.artistId],baseX=i===0?this.w*.25:this.w*.75,y=this.h*.73,attacking=this.hit?.side===i,x=baseX+(attacking?Math.sin(Math.min(prog,1)*Math.PI)*(i===0?this.w*.25:-this.w*.25):0);if(f.isActiveTurn){c.strokeStyle=a.color;c.lineWidth=4;c.globalAlpha=.55+.25*Math.sin(this.time/180);c.beginPath();c.ellipse(x,y+6,65,16,0,0,Math.PI*2);c.stroke();c.globalAlpha=1}c.save();c.translate(x,y);if(i===1)c.scale(-1,1);c.fillStyle='#05070c';c.strokeStyle=a.color;c.lineWidth=4;c.beginPath();c.arc(0,-105,27,0,Math.PI*2);c.moveTo(-26,-78);c.quadraticCurveTo(-60,-20,-45,0);c.lineTo(-20,-5);c.lineTo(-10,-68);c.lineTo(10,-68);c.lineTo(30,-5);c.lineTo(52,0);c.quadraticCurveTo(54,-28,26,-78);c.closePath();c.fill();c.stroke();c.fillStyle=a.color;c.font='700 20px Georgia';c.scale(i===1?-1:1,1);c.textAlign='center';c.fillText(a.nameZh.slice(0,1),0,-98);c.restore();}
 destroy(){this.running=false;removeEventListener('resize',this.resize);}
}
