import { ARTISTS,ARTIST_MAP } from '../data/artists.js';import { QUESTIONS,shuffledQuestion } from '../data/questions.js';import { MODES,AI_DIFFICULTY_CONFIG } from '../data/modes.js';import { createFighter,MOVES,resolveAnswer,decideWinner,SessionScope } from './battle-state.js';import { chooseAiMove,aiAnswersCorrect,aiCounterSucceeds,thinkingTime } from './ai.js';
export class Game{
 constructor(app,renderer,audio){this.app=app;this.renderer=renderer;this.audio=audio;this.scope=null;this.answerLocked=true;this.used=new Set();this.turns=0;this.round=1;this.suddenDeath=false;this.bossPhase=1;}
 start(config){this.endSession();this.config=config;this.scope=new SessionScope();this.used=new Set(config.usedIds||[]);this.turns=0;this.round=1;this.suddenDeath=false;this.bossPhase=1;this.finishing=false;const player=createFighter({id:'p1',playerName:config.p1Name,artistId:config.p1Artist});player.hp=config.carryHp??player.hp;player.energy=config.carryEnergy??0;player.ultimateUnlocked=player.energy>=100;let opponent;
  if(config.mode==='versus')opponent=createFighter({id:'p2',playerName:config.p2Name,artistId:config.p2Artist});else{const bossVariant=ARTIST_MAP[config.p2Artist].bossVariant,maxHp=config.mode==='boss'?(bossVariant?.maxHp||240):100;opponent=createFighter({id:'cpu',type:'cpu',playerName:config.mode==='boss'?`${ARTIST_MAP[config.p2Artist].nameZh}・大師化身`:'樂評人 AI',artistId:config.p2Artist,maxHp});if(config.mode==='boss')opponent.statusEffects=[{id:'shield',value:bossVariant?.shield?.[0]||30}];}
  this.fighters=[player,opponent];this.active=0;this.startedAt=Date.now();this.app.showBattle(this);this.renderer.setBattle(this.fighters,ARTIST_MAP[opponent.artistId].stageId);this.audio.startBgm(config.mode==='boss'?'boss':ARTIST_MAP[opponent.artistId].bgmId);this.beginTurn();}
 endSession(){this.scope?.cancel();this.scope=null;this.answerLocked=true;this.audio.stopBgm();}
 async beginTurn(){if(!this.scope||this.scope.cancelled)return;if(this.isOver())return this.finishRound();this.turns++;if(this.turns>20&&!this.suddenDeath){const winner=decideWinner(...this.fighters);if(winner)return this.finishRound(winner);this.suddenDeath=true;this.app.alert('SUDDEN DEATH','HP 與分數相同，先答錯或逾時者落敗。');}
  this.fighters.forEach((f,i)=>f.isActiveTurn=i===this.active);this.app.updateBattle(this);this.audio.tone('turn');const f=this.fighters[this.active];this.app.setTurn(`${f.playerName} 的回合`,ARTIST_MAP[f.artistId].color);
  if(f.type==='cpu')await this.cpuTurn();else{this.answerLocked=false;this.app.showSkills(this);}}
 selectMove(id){if(this.answerLocked||this.fighters[this.active].type!=='human')return;const fighter=this.fighters[this.active],move=MOVES[id];if(id==='ultimate'&&fighter.energy<100){this.app.toast('能量尚未達到 100');return;}this.answerLocked=true;fighter.currentSkill=id;this.ask(move);}
 ask(move){const pool=QUESTIONS.filter(q=>q.difficulty===move.difficulty&&!this.used.has(q.id)&&(this.config.mode!=='practice'||!this.config.practicePeriod||this.config.practicePeriod==='all'||q.period===this.config.practicePeriod));if(!pool.length)this.used.clear();const next=pool[Math.floor(Math.random()*pool.length)]||QUESTIONS.find(q=>q.difficulty===move.difficulty);this.used.add(next.id);this.currentQuestion=shuffledQuestion(next);this.currentMove=move;const seconds=this.config.mode==='practice'&&this.config.infiniteTime?999:AI_DIFFICULTY_CONFIG[this.config.difficulty||'medium'].playerAnswerTime;this.deadline=Date.now()+seconds*1000;this.answerLocked=false;this.app.showQuestion(this.currentQuestion,seconds);this.tickQuestion(seconds);}
 async tickQuestion(seconds){while(this.scope&&!this.scope.cancelled&&!this.answerLocked){const left=Math.max(0,Math.ceil((this.deadline-Date.now())/1000));this.app.setQuestionTime(left);if(left<=0){this.answerLocked=true;return this.resolvePlayer(-1,true)}if(!await this.scope.delay(200))return;}}
 answer(index){if(this.answerLocked)return;this.answerLocked=true;const correct=index===this.currentQuestion.answerIndex;this.resolvePlayer(index,false,correct);}
 async resolvePlayer(index,timedOut=false,forced){const attacker=this.fighters[this.active],defender=this.fighters[1-this.active],correct=forced??(!timedOut&&index===this.currentQuestion.answerIndex);const result=resolveAnswer({attacker,defender,move:this.currentMove,correct,timedOut,difficulty:this.currentQuestion.difficulty,remainingSeconds:Math.max(0,Math.ceil((this.deadline-Date.now())/1000))});this.app.feedback(correct,timedOut,this.currentQuestion);this.audio.tone(correct?'correct':'wrong');await this.scope.delay(650);if(this.suddenDeath&&!correct){attacker.hp=0;this.app.alert('SUDDEN DEATH K.O.',`${attacker.playerName} 答錯，驟死淘汰`);this.app.updateBattle(this);return this.finishRound(defender);}if(correct){await this.playAttack(this.active,this.currentMove,result.damage);const shield=defender.statusEffects.find(e=>e.id==='shield');if(result.shieldBlocked>0&&shield?.value===0){this.renderer.bossShieldBreak();this.audio.tone('ultimate');this.app.alert('SHIELD BREAK','Boss 畫框護盾碎裂');await this.scope.delay(850);}await this.checkBossPhase();}else if(defender.type==='cpu'&&['single','boss','story','trial'].includes(this.config.mode)){await this.counterPhase();}if(this.config.mode==='practice'){attacker.hp=Math.max(1,attacker.hp);defender.hp=Math.max(1,defender.hp);}this.nextTurn();}
 async playAttack(side,move,damage){if(!this.scope||this.scope.cancelled)return;this.app.hideQuestion();if(move.id==='ultimate')this.audio.duck(2200);if(side===1)this.app.incoming(move,ARTIST_MAP[this.fighters[side].artistId]);if(side===1&&!await this.scope.delay(move.id==='ultimate'?900:550))return;await new Promise(resolve=>this.renderer.attack(side,move,()=>{this.audio.tone(move.id==='ultimate'?'ultimate':'hit');this.app.damageNumber(damage,1-side);this.app.updateBattle(this);resolve();}));await this.scope.delay(move.id==='ultimate'?900:450);}
 async counterPhase(){const difficulty=this.config.difficulty||'medium',cpu=this.fighters[1];this.app.setCpuState('COUNTER CHANCE — 反擊判定');this.audio.tone('warning');if(!await this.scope.delay(650))return;if(aiCounterSucceeds(difficulty)){const move=MOVES.light,damage=Math.max(1,Math.round(move.damage*AI_DIFFICULTY_CONFIG[difficulty].counterDamageScale));this.fighters[0].hp=Math.max(0,this.fighters[0].hp-damage);cpu.damageDealt+=damage;this.fighters[0].damageReceived+=damage;this.app.alert('COUNTER!','CPU 抓住破綻發動輕反擊');await this.playAttack(1,move,damage);}else{this.app.setCpuState('CPU 錯失反擊機會');await this.scope.delay(500);}}
 async cpuTurn(){const cpu=this.fighters[1],player=this.fighters[0];let difficulty=this.config.difficulty||'medium';if(this.config.mode==='boss'){const ratio=cpu.hp/cpu.maxHp;if(ratio<=.35)difficulty='hard';else if(ratio<=.7)difficulty='medium';}this.answerLocked=true;this.app.hideQuestion();this.app.setCpuState('CPU 思考中…');if(!await this.scope.delay(thinkingTime(difficulty)))return;this.app.setCpuState('CPU 選擇招式');const move=chooseAiMove(cpu,player,difficulty);cpu.currentSkill=move.id;if(!await this.scope.delay(500))return;const pool=QUESTIONS.filter(q=>q.difficulty===move.difficulty&&!this.used.has(q.id));const q=pool[Math.floor(Math.random()*pool.length)]||QUESTIONS[0];this.used.add(q.id);this.app.setCpuState(`CPU 正在回答「${move.label}」題目`);if(!await this.scope.delay(700))return;const correct=aiAnswersCorrect(difficulty,q.difficulty);const result=resolveAnswer({attacker:cpu,defender:player,move,correct,difficulty:q.difficulty,remainingSeconds:0});if(correct){this.app.setCpuState('CPU 攻擊準備完成');await this.playAttack(1,move,result.damage);}else{this.app.alert('判斷失誤','CPU 回答錯誤，攻擊落空');this.audio.tone('wrong');await this.scope.delay(800);}this.nextTurn();}
 async checkBossPhase(){if(this.config.mode!=='boss')return;const boss=this.fighters[1],variant=ARTIST_MAP[boss.artistId].bossVariant,ratio=boss.hp/boss.maxHp,next=ratio<=.35?3:ratio<=.7?2:1;if(next<=this.bossPhase)return;this.bossPhase=next;const shieldValue=variant?.shield?.[next-1]||(next===3?35:25),shield=boss.statusEffects.find(e=>e.id==='shield');if(shield)shield.value+=shieldValue;else boss.statusEffects.push({id:'shield',value:shieldValue});if(next===3){boss.energy=100;boss.ultimateUnlocked=true;}this.audio.tone('ultimate');this.renderer.bossTransition(next);this.app.alert(variant?.phaseNames?.[next-1]||`BOSS PHASE ${next}`,next===3?'最終階段：護盾重生，大絕招準備完成':'樂章轉換：專屬護盾恢復');await this.scope.delay(1700);}
 nextTurn(){if(!this.scope||this.scope.cancelled)return;if(this.isOver())return this.finishRound();this.active=1-this.active;this.beginTurn();}
  isOver(){return this.fighters.some(f=>f.hp<=0);}
 finishRound(forcedWinner){if(!this.scope)return;const winner=forcedWinner||this.fighters.find(f=>f.hp>0)||decideWinner(...this.fighters);if(!winner){this.suddenDeath=true;return this.beginTurn();}winner.roundsWon++;const needed=this.config.roundsToWin||1;if(winner.roundsWon>=needed)return this.finish(winner);const loser=this.fighters.find(f=>f!==winner);this.round++;this.turns=0;this.suddenDeath=false;for(const f of this.fighters){f.hp=f.maxHp;f.energy=0;f.combo=0;f.currentSkill=null;f.ultimateUnlocked=false;f.isActiveTurn=false;}this.active=(this.round-1)%2;this.app.roundTransition(this,winner,loser,()=>this.beginTurn());}
 finish(forcedWinner){if(!this.scope||this.finishing)return;const winner=forcedWinner||this.fighters.find(f=>f.hp>0)||decideWinner(...this.fighters);if(!winner)return;const loser=this.fighters.find(f=>f!==winner);this.finishing=true;this.audio.tone('ko');if(this.config.mode==='boss'&&loser.id==='cpu'){this.renderer.bossDefeat();this.app.alert('MAESTRO FINALE','終章落幕，大師挑戰完成');const scope=this.scope;scope.delay(1550).then(ok=>{if(ok)this.completeFinish(winner,loser)});return;}this.completeFinish(winner,loser);}
 completeFinish(winner,loser){if(!this.scope)return;this.app.finishBattle(this,winner,loser);this.endSession();}
}
